obstacle_range: 3.0
raytrace_range: 3.5
footprint: [[-0.25, 0.25], [0.25, 0.25], [0.25, -0.3], [-0.25, -0.3]]
#robot_radius: 0.3
inflation_radius: 0.6

observation_sources: laser_scan_sensor #point_cloud_sensor

laser_scan_sensor: {sensor_frame: hokuyo_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}
